unit ufrmAsset;

interface

uses
  Winapi.Windows, Winapi.Messages, System.SysUtils, System.Variants, System.Classes, Vcl.Graphics,
  Vcl.Controls, Vcl.Forms, Vcl.Dialogs, Vcl.ExtCtrls, Vcl.Imaging.pngimage,
  Vcl.StdCtrls, Vcl.Mask, Vcl.Buttons, Vcl.ComCtrls,

  {uses project}
   uSimMgr_Client, uLibSetting, uClassData, uDataModule, uRecordData;

type
  TfrmAsset = class(TForm)
    pnlMain: TPanel;
    imgBackgroundForm: TImage;
    pnl1Title: TPanel;
    txtClass: TLabel;
    edtClass: TEdit;
    pnl2ControlPage: TPanel;
    pgc: TPageControl;
    tsGeneral: TTabSheet;
    lbl3: TLabel;
    lbl4: TLabel;
    lbl5: TLabel;
    lbl6: TLabel;
    Label134: TLabel;
    Label135: TLabel;
    Label136: TLabel;
    lbl12: TLabel;
    lbl13: TLabel;
    lblNames: TLabel;
    imgInsert: TImage;
    imgRemove: TImage;
    imgEdit: TImage;
    cbbCategory: TComboBox;
    cbbType: TComboBox;
    cbbDetectabilityType: TComboBox;
    lstName: TListBox;
    cbbDomain: TComboBox;
    edtQuantityGroupPersonal: TEdit;
    grbCapabilities: TGroupBox;
    chkNavigation: TCheckBox;
    chkBarrier: TCheckBox;
    grbCommunication: TGroupBox;
    lblAntennaHeight: TLabel;
    lblAntennaAboveWater: TLabel;
    lblMaxCommDepth: TLabel;
    mn1: TLabel;
    mn2: TLabel;
    mn3: TLabel;
    lblLink: TLabel;
    lblVoice: TLabel;
    lblMessage: TLabel;
    chkHFLink: TCheckBox;
    chkUHFLink: TCheckBox;
    chkHFVoice: TCheckBox;
    chkUHFVoice: TCheckBox;
    chkSatcom: TCheckBox;
    chkUnderwater: TCheckBox;
    chkHFMessageHandling: TCheckBox;
    chkUHFMessageHandling: TCheckBox;
    chkSATCOMMessageHAndling: TCheckBox;
    edtAntennaHeight: TEdit;
    edtAntennaAboveWater: TEdit;
    edtMaxCom: TEdit;
    grbDamage: TGroupBox;
    mnlbl10: TLabel;
    mnlbl11: TLabel;
    trckbrDamageSustainability: TTrackBar;
    edtDamageSustainability: TEdit;
    tsModel: TTabSheet;
    lbl23: TLabel;
    Image: TImage;
    grp1: TGroupBox;
    lbl15: TLabel;
    lbl16: TLabel;
    lbl18: TLabel;
    lbl19: TLabel;
    edtSymbolID: TEdit;
    edtVBSClassName: TEdit;
    grp2: TGroupBox;
    btnTacticalSymbol: TSpeedButton;
    lbl14: TLabel;
    lbl24: TLabel;
    lblFontTaktis: TLabel;
    lblKeteranganSymbol: TLabel;
    Label2: TLabel;
    sButton1: TSpeedButton;
    cbbFontType: TComboBox;
    edtFontID: TEdit;
    edtModelPath: TEdit;
    tsPhysical: TTabSheet;
    lblMotionCharacteristic: TLabel;
    lblCroosSection: TLabel;
    GroupBox1: TGroupBox;
    Label8: TLabel;
    Label9: TLabel;
    Label11: TLabel;
    Label12: TLabel;
    Label14: TLabel;
    Label15: TLabel;
    lbl26: TLabel;
    lbl27: TLabel;
    Label10: TLabel;
    Label13: TLabel;
    Label16: TLabel;
    lbl28: TLabel;
    Label17: TLabel;
    Label19: TLabel;
    Label18: TLabel;
    Label23: TLabel;
    Label24: TLabel;
    Label25: TLabel;
    lbl22: TLabel;
    lbl29: TLabel;
    edtLengthDimension: TEdit;
    edtWidthDimension: TEdit;
    edtHeightDimension: TEdit;
    edtWeightDimension: TEdit;
    edtEngagementRangeDimension: TEdit;
    edtDraftDimension: TEdit;
    Edit1: TEdit;
    Button1: TButton;
    cbGangwayFront: TCheckBox;
    cbGangwayRear: TCheckBox;
    cbGangwayPort: TCheckBox;
    cbGangwayStarboard: TCheckBox;
    edtMotionCharacterictic: TEdit;
    btnMotionCharacteristic: TButton;
    grbAcousticIntensityPhysical: TGroupBox;
    lblMinimumSpeed: TLabel;
    lblBelowCavitation: TLabel;
    lblAboveCavitation: TLabel;
    lblMaximumSpeed: TLabel;
    mn10: TLabel;
    mn11: TLabel;
    mn12: TLabel;
    mn13: TLabel;
    lblCavitationSpeed: TLabel;
    mn14: TLabel;
    edtMinSpeedAcousticPhysical: TEdit;
    edtBelowCavitationAcousticPhysical: TEdit;
    edtAboveCavitationAcousticPhysical: TEdit;
    edtMaxSpeedAcousticPhysical: TEdit;
    edtCavitationSpeedAcousticPhysical: TEdit;
    grbRadarPhysical: TGroupBox;
    lblRadarFront: TLabel;
    lblRadarSide: TLabel;
    edtFrontRadarPhysical: TEdit;
    cbbFrontRadarPhysical: TComboBox;
    edtSideRadarPhysical: TEdit;
    cbbSideRadarPhysical: TComboBox;
    grbAcousticPhysical: TGroupBox;
    lblAcousticFront: TLabel;
    lblAcousticSide: TLabel;
    mn4: TLabel;
    mn5: TLabel;
    edtFrontAcousticPhysical: TEdit;
    edtSideAcousticPhysical: TEdit;
    grbVisualPhysical: TGroupBox;
    lblVisualEOFront: TLabel;
    lblVisualEOSide: TLabel;
    mn6: TLabel;
    mn7: TLabel;
    edtFrontVisualPhysical: TEdit;
    edtSideVisualPhysical: TEdit;
    grbInfraredPhysical: TGroupBox;
    lblInfraredFront: TLabel;
    lblInfraredSide: TLabel;
    mn8: TLabel;
    mn9: TLabel;
    edtFrontInfraredPhysical: TEdit;
    edtSideInfraredPhysical: TEdit;
    grbMagneticPhysical: TGroupBox;
    edtMagneticPhysical: TEdit;
    tsCharacteristic: TTabSheet;
    grbAirDropLimitation: TGroupBox;
    lblMaxDropAltitude: TLabel;
    lblMinDropAltitude: TLabel;
    lblMaxDropSpeed: TLabel;
    mn20: TLabel;
    mn21: TLabel;
    mn22: TLabel;
    edtMaxDropAltitude: TEdit;
    edtMinDropAltitude: TEdit;
    edtMaxDropSpeed: TEdit;
    grbSonobuoyCapable: TGroupBox;
    mnMaxNumToMonitor: TLabel;
    mnMaxDeployAltitude: TLabel;
    mnMinDeployAltitude: TLabel;
    mn25: TLabel;
    mn26: TLabel;
    lblMaxDeploySpeed: TLabel;
    mn27: TLabel;
    edtMaxNumbToMonitor: TEdit;
    edtMaxDeployAltitude: TEdit;
    edtMinDeployAltitude: TEdit;
    edtMaxDeploySpeed: TEdit;
    grbFlowNoiseFactors: TGroupBox;
    lblHMS: TLabel;
    mnTAS: TLabel;
    mn23: TLabel;
    mn24: TLabel;
    edtHullMounted: TEdit;
    edtTowedArray: TEdit;
    chkSonobuoyCapable: TCheckBox;
    tsPOH: TTabSheet;
    grbMissile: TGroupBox;
    lblARHoming: TLabel;
    lblIRHoming: TLabel;
    lblSARH: TLabel;
    lblTARH: TLabel;
    mn28: TLabel;
    mn29: TLabel;
    edtAntiRadiationMissile: TEdit;
    edtInfraredHomingMissile: TEdit;
    edtSemiActiveMissile: TEdit;
    edtTerminalActiveMissile: TEdit;
    trckbrAntiRadiationMissile: TTrackBar;
    trckbrInfraredMissile: TTrackBar;
    trckbrSemiActiveMissile: TTrackBar;
    trckbrTerminalActiveMissile: TTrackBar;
    grbMine: TGroupBox;
    lblAcousticMine: TLabel;
    lblImpactMine: TLabel;
    lblMagneticMine: TLabel;
    lblPressureMine: TLabel;
    mn32: TLabel;
    mn33: TLabel;
    edtAcousticMine: TEdit;
    edtImpactMine: TEdit;
    edtMagneticMine: TEdit;
    edtPressureMine: TEdit;
    trckbrAcousticMine: TTrackBar;
    trckbrImpactMine: TTrackBar;
    trckbrMagneticMine: TTrackBar;
    trckbrPressureMine: TTrackBar;
    grbTorpedo: TGroupBox;
    lblActiveHoming: TLabel;
    lblPassiveHoming: TLabel;
    lblActivePassiveHoming: TLabel;
    lblWireGuided: TLabel;
    mn30: TLabel;
    mn31: TLabel;
    lblWakeHoming: TLabel;
    edtActiveAcousticTorpedo: TEdit;
    edtPassiveAcousticTorpedo: TEdit;
    edtActivePassiveAcousticTorpedo: TEdit;
    edtWireGuidedTorpedo: TEdit;
    trckbrActiveAcousticTorpedo: TTrackBar;
    trckbrPassiveAcousticTorpedo: TTrackBar;
    trckbrActivePassiveAcousticTorpedo: TTrackBar;
    trckbrWireGuidedTorpedo: TTrackBar;
    edtWakeHomingTorpedo: TEdit;
    trckbrWakeHomingTorpedo: TTrackBar;
    tsAssets: TTabSheet;
    btnDefaultLogistics: TSpeedButton;
    lbl20: TLabel;
    lbl21: TLabel;
    btnCCapability: TSpeedButton;
    grpBasing: TGroupBox;
    btnHelicopterLimitations: TButton;
    cmbBasingType: TComboBox;
    grpReadyingTime: TGroupBox;
    labelRefuel: TLabel;
    Label54: TLabel;
    Label55: TLabel;
    Label56: TLabel;
    edtRefuelTime: TMaskEdit;
    edtLaunchAlertTime: TMaskEdit;
    grbSensor: TGroupBox;
    btnRadar: TButton;
    btnMAD: TButton;
    btnESM: TButton;
    btnSonar: TButton;
    btnElectroOpticalDetector: TButton;
    btnIFF: TButton;
    btnVisualDetector: TButton;
    btnSonobuoy: TButton;
    grbWeapons: TGroupBox;
    btnMissiles: TButton;
    btnTorpedos: TButton;
    btnMines: TButton;
    btnGuns: TButton;
    btnBomb_DepthCharges: TButton;
    grbCountermeasures: TGroupBox;
    btnRadarJummer: TButton;
    btnAirBubble: TButton;
    btnAccousticDecoy: TButton;
    btnDefensiveJummer: TButton;
    btnTowedJummer_Decoy: TButton;
    btnFloatingDecoy: TButton;
    btnChaff: TButton;
    btnInfraredDecoy: TButton;
    edtDefaultLogistics: TEdit;
    edtDefaultCarryingCap: TEdit;
    btnEmbarkedPlatforms: TButton;
    tsPeriscope: TTabSheet;
    lblPeriscopeRadarMastCrossSection: TLabel;
    grbPeriscope: TGroupBox;
    lblMaxOperatingDepth: TLabel;
    mn37: TLabel;
    mn38: TLabel;
    lblHighAboveWater: TLabel;
    edtMaxOperatPeriscope: TEdit;
    edtHighAbovePeriscope: TEdit;
    grbRadar: TGroupBox;
    lblPeriscopeRadarFront: TLabel;
    lblPeriscopeRadarSide: TLabel;
    edtFrontRadar: TEdit;
    edtSideRadar: TEdit;
    cbbFontRadar: TComboBox;
    cbbSideRadar: TComboBox;
    grbInfrared: TGroupBox;
    lblPeriscopeInfraredFront: TLabel;
    lblPeriscopeInfraredSide: TLabel;
    mn39: TLabel;
    mn40: TLabel;
    edtFrontInfrared: TEdit;
    edtSideInfrared: TEdit;
    grbVisual: TGroupBox;
    lblPeriscopeVisualFront: TLabel;
    lblPeriscopeVisualSide: TLabel;
    mn41: TLabel;
    mn42: TLabel;
    edtFrontVisual: TEdit;
    edtSideVisual: TEdit;
    tsNotes: TTabSheet;
    mmoNotes: TMemo;
    lblPlatform: TLabel;
    btnOK: TImage;
    btnApply: TImage;
    btnCancel: TImage;
    procedure btnOKClick(Sender: TObject);
    procedure btnCancelClick(Sender: TObject);

  private
    FSelectedAsset : TAsset ;

  public
    isOK : Boolean;
    afterClose : Boolean;

    property SelectedAsset : TAsset read FSelectedAsset write FSelectedAsset;
  end;

var
  frmAsset: TfrmAsset;

implementation

{$R *.dfm}

procedure TfrmAsset.btnCancelClick(Sender: TObject);
begin
  afterClose := False;
  Close;
end;

procedure TfrmAsset.btnOKClick(Sender: TObject);
begin
  if btnOK.Enabled then
    btnOK.Click;

  if isOK then
    Close;

end;

end.
